using System;
using System.Collections.Generic;
using System.Text;

namespace Thinktecture.Tools.Web.Services.CodeGeneration
{
    /// <summary>
    /// This class defines the data structure used to return the CodeWriter output.
    /// </summary>
    public class CodeWriterOutput
    {
        #region Private fields
        
        private string[] codeFileNames;
        private string configurationFile;

        #endregion

        #region Constructors

        internal CodeWriterOutput(string[] codeFileNames, string configurationFile)
        {
            this.codeFileNames = codeFileNames;
            this.configurationFile = configurationFile;
        }

        #endregion

        #region Public properties

        /// <summary>
        /// Gets a list of strings containing the file names generated by the code writer.
        /// </summary>
        public string[] CodeFileNames
        {
            get { return codeFileNames; }
        }

        /// <summary>
        /// Gets the generated configuration file.
        /// </summary>
        public string ConfigurationFile
        {
            get { return configurationFile; }
        }

        #endregion
    }
}
